---
title: "Research Discussion Assignment 4"
author: "Joseph E. Garcia"
date: "June 29, 2019"
output: html_document
---
Mitigating the Harm of Recommender Systems

Read one or more of the articles below and consider how to counter the radicalizing effects of recommender systems or ways to prevent algorithmic discrimination.

I think that If the content is not violent, maybe require recommendations of different perspectives. It is my understanding that the key to mitigate radicalization is diversity and the key to diversity is to somehow prevent groups with radical ideas from forming cliques.to understand before trying to counter radicalization in recommender systems is what radicalization is and how it works. I think that begins with understanding that is a difference between "extremism" and "radicalization." The terms are used interchangeably because they describe attitudes that deviate from society's norm. But they are not the same. Extremism is more along the lines of a belief/support of far-reaching changes in society that pose a threat to the democratic order, while radicalization is the development of ideas that are fundamentally different from an individual's educational environment or disagree with the mainstream.

References:

Renee Diresta, Wired.com (2018): Up Next: A Better Recommendation System

Zeynep Tufekci, The New York Times (2018): YouTube, the Great Radicalizer

Sanjay Krishnan, Jay Patel, Michael J. Franklin, Ken Goldberg (n/a): Social Influence Bias in Recommender Systems: A Methodology for Learning, Analyzing, and Mitigating Bias in Ratings

